# Generated by Django 3.2.9 on 2021-11-12 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateField(auto_now=True, verbose_name='Оновлено')),
                ('image', models.ImageField(upload_to='task_images/', verbose_name='Фотографія')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task_is_set_to', models.ManyToManyField(related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кому поставлена задача')),
            ],
        ),
    ]
